name: com_ramabit_www
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_side_menu: ^0.4.0
  http: ^1.2.1
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  bootstrap_icons: ^1.11.3
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  syncfusion_flutter_charts: ^25.1.39+1
  fl_chart: ^0.67.0
  flutter_secure_storage: ^9.0.0
  file_picker: ^8.0.1
  flutter_exit_app: ^1.1.2
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: sansir
      fonts:
        - asset: fonts/IranianSans.ttf
          style: normal

  assets:
    - images/